import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
import Footer from "@/components/footer";
import ProviderWrapper from "@/app/components/csrWrapper/ProviderWrapper"; // ProviderWrapper 가져오기

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Moving Movie",
    description: "Generated by TEAM 1",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <ProviderWrapper>{children}</ProviderWrapper>
                <Footer />
            </body>
        </html>
    );
}
