name: Deploy NestJS App

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: be/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/be/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --prefix be

      - name: Build project
        run: npm run build --prefix be

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd project/be
            git pull origin main
            npm install
            npm run build
            pm2 restart nestjs-app
